keys:
  - &desktop-key age10n49wavc547hh36jhvhg2dehn68vlp38v5jlwf5s6pelrjd4v57symt274
  - &laptop-key age1pr6fa39zzg09exqtnq2ajcth52vv656uhpmhg4u7q6zck3chyyrsl7dupm
  - &thinkpad-key age15z7pvz52sfs9vqmprf3ys72jjfd0gunmvx9grakcrzw5h7m02swq7yfuy0

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *desktop-key
      - *laptop-key
      - *thinkpad-key
