keys:
  - &desktop-key age10n49wavc547hh36jhvhg2dehn68vlp38v5jlwf5s6pelrjd4v57symt274

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *desktop-key